### ISSUE TITLE
ERR Failed to create new quic connection error

### ISSUE THREAD

**Issue by vladaurosh** [SanCraftDev/cloudflared#79]
This one was closed
https://github.com/ZoeyVid/cloudflared/issues/76
so just opening new one for the same issue. 
Official 2024.1.5 docker image has this resolved,  but still having issue with this image.
Looks like official image uses go1.21.5-devel-cf and this one go1.21.6, and according to https://github.com/cloudflare/cloudflared/issues/1143 that's causing the issue.

**Comment by Zoey2936** [comment]
sorry, but the issue you mentined doesn't talk abouts go versions

**Comment by vladaurosh** [comment]
Actually it does.
In https://github.com/cloudflare/cloudflared/issues/1143 you can see message 
related https://github.com/cloudflare/cloudflared/issues/1132 where you can see following:
```
Ok a valid release [2024.1.1](https://github.com/cloudflare/cloudflared/releases/tag/2024.1.1) was issued. All binaries and docker images are working. Sorry for the inconvenience but because of the go update to 1.21 and the Post Quantum ciphers we had to start using [cloudflare go toolchain](https://github.com/cloudflare/go) which was not spread across all of our builds. We will work to improve the process in the future and ensure this won't happen again.

It is now also possible to build locally using make install which will use the cloudflare go toolchain.
```

**Comment by Zoey2936** [comment]
so cloudflare use their own fork of go and offical go doesn't work?

**Comment by Zoey2936** [comment]
should be fixed in the next release
