### ISSUE TITLE
mikrotik

### ISSUE THREAD

**Issue by zstergios** [SanCraftDev/cloudflared#90]
The original tunnel code is:
cloudflare/cloudflared:latest tunnel --no-autoupdate run --token xxxxxx

I replaced the code on mikrotik with:

zoeyvid/cloudflared:latest --no-autoupdate run --token xxxxxx

Seems is running but not working.

What's the command I should use?

The reason I am using your docker is that supports ARM x86

**Comment by Zoey2936** [comment]
try `zoeyvid/cloudflared:latest tunnel run --token xxxxxx`
